-- Minimal Supabase/PostgreSQL schema for user-created communities and short videos.
-- Run this in the Supabase SQL editor after confirming the existing users/posts tables exist.

create table if not exists public.communities (
  id bigint generated by default as identity primary key,
  name varchar(80) not null,
  slug varchar(64) not null unique,
  description varchar(240) default '',
  owner_id bigint not null references public.users(id) on delete cascade,
  accent_color char(7) not null default '#1D9BF0',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.community_members (
  community_id bigint not null references public.communities(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role varchar(20) not null default 'member',
  created_at timestamptz not null default now(),
  primary key (community_id, user_id)
);

create table if not exists public.community_posts (
  community_id bigint not null references public.communities(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (community_id, post_id)
);

create table if not exists public.community_videos (
  id bigint generated by default as identity primary key,
  community_id bigint not null references public.communities(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  video_url text not null,
  caption varchar(180) default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_communities_owner on public.communities(owner_id);
create index if not exists idx_community_members_user on public.community_members(user_id);
create index if not exists idx_community_posts_created on public.community_posts(community_id, created_at desc);
create index if not exists idx_community_videos_created on public.community_videos(community_id, created_at desc);
