-- LvL product hardening migration.
-- Run in Supabase SQL editor after the base users/posts/messages tables exist.

alter table public.users
  add column if not exists onboarding_completed boolean not null default false,
  add column if not exists interests text default '';

alter table public.posts
  add column if not exists image_url text,
  add column if not exists deleted_at timestamptz;

create table if not exists public.user_safety_actions (
  id bigint generated by default as identity primary key,
  actor_id bigint not null references public.users(id) on delete cascade,
  target_user_id bigint not null references public.users(id) on delete cascade,
  post_id bigint references public.posts(id) on delete set null,
  action_type text not null check (action_type in ('report', 'block', 'mute')),
  reason varchar(280) default '',
  created_at timestamptz not null default now(),
  constraint no_self_safety_action check (actor_id <> target_user_id)
);

create unique index if not exists idx_user_safety_unique_user_action
  on public.user_safety_actions(actor_id, target_user_id, action_type)
  where post_id is null;

create unique index if not exists idx_user_safety_unique_post_report
  on public.user_safety_actions(actor_id, target_user_id, post_id, action_type)
  where post_id is not null;

create unique index if not exists idx_follows_unique_pair
  on public.follows(follower_id, following_id);

create unique index if not exists idx_likes_unique_pair
  on public.likes(user_id, post_id);

create unique index if not exists idx_reposts_unique_pair
  on public.reposts(user_id, post_id);

create unique index if not exists idx_friendships_unique_pair
  on public.friendships(user_1, user_2);

create index if not exists idx_posts_created_visible
  on public.posts(created_at desc)
  where deleted_at is null;

create index if not exists idx_messages_pair_created
  on public.messages(sender_id, receiver_id, created_at desc);

create index if not exists idx_notifications_user_read
  on public.notifications(user_id, is_read, created_at desc);
