-- First-class Reels tables for LvL.
-- Run in Supabase SQL editor after users and communities tables exist.

create table if not exists public.reels (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  community_id bigint null references public.communities(id) on delete set null,
  video_url text not null,
  storage_path text null,
  cover_url text null,
  caption varchar(220) default '',
  visibility text not null default 'public'
    check (visibility in ('public', 'followers', 'community', 'private')),
  allow_comments boolean not null default true,
  allow_downloads boolean not null default false,
  autoplay_next boolean not null default true,
  status text not null default 'active'
    check (status in ('active', 'hidden', 'deleted')),
  view_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create table if not exists public.reel_likes (
  reel_id bigint not null references public.reels(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (reel_id, user_id)
);

create table if not exists public.reel_comments (
  id bigint generated by default as identity primary key,
  reel_id bigint not null references public.reels(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  comment varchar(280) not null,
  created_at timestamptz default now(),
  deleted_at timestamptz null
);

create table if not exists public.reel_views (
  id bigint generated by default as identity primary key,
  reel_id bigint not null references public.reels(id) on delete cascade,
  user_id bigint null references public.users(id) on delete set null,
  created_at timestamptz default now()
);

create index if not exists idx_reels_created_active
  on public.reels(created_at desc)
  where deleted_at is null and status = 'active';

create index if not exists idx_reels_user_created
  on public.reels(user_id, created_at desc);

create index if not exists idx_reels_community_created
  on public.reels(community_id, created_at desc);

create index if not exists idx_reel_likes_reel
  on public.reel_likes(reel_id);

create index if not exists idx_reel_comments_reel_created
  on public.reel_comments(reel_id, created_at desc);

create index if not exists idx_reel_views_reel_created
  on public.reel_views(reel_id, created_at desc);
