-- ============================================================
-- Migration 003: Safety actions table + demo content
-- Run this in the Supabase SQL Editor.
-- Safe to run multiple times (all statements use IF NOT EXISTS).
-- ============================================================

-- ─── REQUIRED: user_safety_actions table ────────────────────────────────────
-- Needed for Mute and Block to work.

create table if not exists public.user_safety_actions (
  id bigint generated by default as identity primary key,
  actor_id bigint not null references public.users(id) on delete cascade,
  target_user_id bigint not null references public.users(id) on delete cascade,
  post_id bigint references public.posts(id) on delete set null,
  action_type text not null check (action_type in ('report', 'block', 'mute')),
  reason varchar(280) default '',
  created_at timestamptz not null default now(),
  constraint no_self_safety_action check (actor_id <> target_user_id)
);

create unique index if not exists idx_user_safety_unique_user_action
  on public.user_safety_actions(actor_id, target_user_id, action_type)
  where post_id is null;

create unique index if not exists idx_user_safety_unique_post_report
  on public.user_safety_actions(actor_id, target_user_id, post_id, action_type)
  where post_id is not null;

-- ─── REQUIRED: RLS for user_safety_actions ──────────────────────────────────
alter table public.user_safety_actions enable row level security;

-- Service key (backend) bypasses RLS, so only browser anon calls are restricted:
do $$ begin
  if not exists (
    select 1 from pg_policies
    where tablename = 'user_safety_actions' and policyname = 'safety_actions_own_actor'
  ) then
    execute 'create policy safety_actions_own_actor on public.user_safety_actions
      for all using (actor_id = (select id from public.users where id = actor_id))';
  end if;
end $$;

-- ─── OPTIONAL: Add is_demo column to users table ────────────────────────────
-- Used to mark demo/seed users. Does not affect existing rows.

alter table public.users
  add column if not exists is_demo boolean not null default false;

-- ─── OPTIONAL: Demo content ─────────────────────────────────────────────────
-- Inserts 3 demo users, posts, likes, follows, reels, and notifications.
-- All demo rows are marked with is_demo = true (users) or have content starting
-- with '[DEMO]' so they can be identified and cleaned up later.
-- Skip this block if you already have real content.

do $$
declare
  u1 bigint; u2 bigint; u3 bigint;
  p1 bigint; p2 bigint; p3 bigint;
  r1 bigint; r2 bigint;
begin
  -- Demo users (only insert if they don't already exist by username)
  insert into public.users (username, nickname, display_name, email, password_hash, is_demo, level)
    values ('demo_alex', 'demo_alex', 'Alex Demo', 'demo_alex@lvl.local', 'demo_nologin', true, 3)
    on conflict (username) do nothing;
  select id into u1 from public.users where username = 'demo_alex';

  insert into public.users (username, nickname, display_name, email, password_hash, is_demo, level)
    values ('demo_sam', 'demo_sam', 'Sam Demo', 'demo_sam@lvl.local', 'demo_nologin', true, 5)
    on conflict (username) do nothing;
  select id into u2 from public.users where username = 'demo_sam';

  insert into public.users (username, nickname, display_name, email, password_hash, is_demo, level)
    values ('demo_riley', 'demo_riley', 'Riley Demo', 'demo_riley@lvl.local', 'demo_nologin', true, 2)
    on conflict (username) do nothing;
  select id into u3 from public.users where username = 'demo_riley';

  if u1 is null or u2 is null or u3 is null then
    raise notice 'Demo users already exist, skipping demo content.';
    return;
  end if;

  -- Demo posts
  insert into public.posts (user_id, content)
    values (u1, '[DEMO] Welcome to LvL! This is a sample post from Alex. 🎮')
    returning id into p1;

  insert into public.posts (user_id, content)
    values (u2, '[DEMO] Sam here! LvL is the place to level up your social game. 🚀')
    returning id into p2;

  insert into public.posts (user_id, content)
    values (u3, '[DEMO] Just joined LvL! Excited to be here. 🌟')
    returning id into p3;

  -- Demo follows: u2 follows u1, u3 follows u1
  insert into public.follows (follower_id, following_id) values (u2, u1) on conflict do nothing;
  insert into public.follows (follower_id, following_id) values (u3, u1) on conflict do nothing;
  insert into public.follows (follower_id, following_id) values (u1, u2) on conflict do nothing;

  -- Demo likes
  insert into public.likes (user_id, post_id) values (u2, p1) on conflict do nothing;
  insert into public.likes (user_id, post_id) values (u3, p1) on conflict do nothing;
  insert into public.likes (user_id, post_id) values (u1, p2) on conflict do nothing;

  -- Demo comments
  insert into public.comments (user_id, post_id, comment) values (u2, p1, '[DEMO] Great first post!');
  insert into public.comments (user_id, post_id, comment) values (u3, p2, '[DEMO] Love the energy!');

  -- Demo reposts
  insert into public.reposts (user_id, post_id) values (u3, p1) on conflict do nothing;

  -- Demo reels (using CC0 video)
  insert into public.reels (user_id, video_url, caption, status, visibility, autoplay_next)
    values (u1, 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
            '[DEMO] Alex''s first reel on LvL!', 'active', 'public', true)
    returning id into r1;

  insert into public.reels (user_id, video_url, caption, status, visibility, autoplay_next)
    values (u2, 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
            '[DEMO] Sam''s reel — keep leveling up!', 'active', 'public', true)
    returning id into r2;

  -- Demo notifications
  insert into public.notifications (user_id, actor_id, type)
    values (u1, u2, 'follow');
  insert into public.notifications (user_id, actor_id, type, post_id)
    values (u1, u3, 'like', p1);

  raise notice 'Demo content inserted: users %, %, %', u1, u2, u3;
end $$;


-- ─── CLEANUP SQL (run separately when you want to remove demo data) ──────────
-- Copy and run this block independently to remove all demo content.
/*

do $$
declare
  demo_ids bigint[];
begin
  select array_agg(id) into demo_ids from public.users where is_demo = true;
  if demo_ids is null then
    raise notice 'No demo users found.';
    return;
  end if;

  -- Remove reels
  delete from public.reel_likes  where user_id = any(demo_ids);
  delete from public.reel_comments where user_id = any(demo_ids);
  delete from public.reel_views  where user_id = any(demo_ids);
  delete from public.reels       where user_id = any(demo_ids);

  -- Remove posts and related
  delete from public.comments    where user_id = any(demo_ids);
  delete from public.likes       where user_id = any(demo_ids);
  delete from public.reposts     where user_id = any(demo_ids);
  delete from public.posts       where user_id = any(demo_ids);

  -- Remove social graph
  delete from public.follows     where follower_id = any(demo_ids) or following_id = any(demo_ids);
  delete from public.friendships where user_1 = any(demo_ids) or user_2 = any(demo_ids);
  delete from public.notifications where user_id = any(demo_ids) or actor_id = any(demo_ids);
  delete from public.messages    where sender_id = any(demo_ids) or receiver_id = any(demo_ids);
  delete from public.user_safety_actions where actor_id = any(demo_ids) or target_user_id = any(demo_ids);

  -- Finally remove users
  delete from public.users where id = any(demo_ids);

  raise notice 'Removed % demo users and all their content.', array_length(demo_ids, 1);
end $$;

*/
