-- ============================================================
-- Migration 004: User streaks
-- Run in Supabase SQL Editor. Safe to run multiple times.
-- ============================================================

create table if not exists public.user_streaks (
  id bigint generated by default as identity primary key,
  user_1 bigint not null references public.users(id) on delete cascade,
  user_2 bigint not null references public.users(id) on delete cascade,
  streak_count int not null default 1,
  last_streak_date date not null default current_date,
  updated_at timestamptz not null default now(),
  constraint user_streaks_ordered check (user_1 < user_2),
  constraint user_streaks_no_self check (user_1 <> user_2)
);

create unique index if not exists idx_user_streaks_pair
  on public.user_streaks(user_1, user_2);

create index if not exists idx_user_streaks_user_1
  on public.user_streaks(user_1);

create index if not exists idx_user_streaks_user_2
  on public.user_streaks(user_2);

-- RLS: users can read their own streaks; backend service key writes
alter table public.user_streaks enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where tablename = 'user_streaks' and policyname = 'streaks_read_own'
  ) then
    execute 'create policy streaks_read_own on public.user_streaks
      for select using (
        user_1 = (select id from public.users where id = user_1)
        or user_2 = (select id from public.users where id = user_2)
      )';
  end if;
end $$;

-- XP events dedup index (if not already present from prior migrations)
create unique index if not exists idx_xp_events_dedup
  on public.xp_events(user_id, event_type, event_key);
