-- Migration to add like and repost functionality to comments
create table if not exists public.comment_likes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  comment_id bigint not null references public.comments(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_comment_likes_unique_pair
  on public.comment_likes(user_id, comment_id);

create table if not exists public.comment_reposts (
  user_id bigint not null references public.users(id) on delete cascade,
  comment_id bigint not null references public.comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, comment_id)
);
